input:
  syslog:
  - name: "some_syslog_input"
    listenAddr: ":20000"
  api:
  - name: "some_api_input"
    listenAddr: ":9999"
    path: "/my/api"
template:
  type: plain
  pattern: "{{.remote_addr}} | {{.remote_user}} | {{.time_local}} | {{.request}} | {{.status}} | {{.body_bytes_sent}} | {{.http_referer}} | {{.http_user_agent}}"
  delimiter: "|"
metrics:
- name: handler_total_requests
  type: counterVec
  help: "Total requests by handler"
  value: 1
  labels:
  - name: "status"
    value: "{{.status}}"
  - name: "handler"
    values:
    - expr: "{{if contains .request `blog`}}1{{end}}"
      value: "{{ extractRegExp `\\/blog\\/[a-zA-Z-_\\/]+` .request }}"
    - expr: "{{if eq .request `/`}}1{{end}}"
      value: "home"
    - value: "{{if contains .request `forum`}}{{ extractRegExp `\\/forum\\/[a-zA-Z-_\\/]+` .request }}{{end}}"
