input:
  syslog:
  - name: "some_syslog_input"
    listenAddr: ":20000"
  api:
  - name: "some_api_input"
    listenAddr: ":9999"
    path: "/my/api"
template:
  type: plain
  pattern: "{{.remote_addr}} | {{.remote_user}} | {{.time_local}} | {{.request}} | {{.status}} | {{.body_bytes_sent}} | {{.http_referer}} | {{.http_user_agent}}"
  delimiter: "|"
metrics:
- name: requests_total
  type: counter
  help: "Total requests"
  expr: '{{if ne .request "1"}}1{{end}}'
  value: "1"
- name: status_requests_total
  type: counterVec
  help: "Total requests statsu"
  expr: '{{if ne .status ""}}1{{end}}'
  labels:
  - name: "status"
    value: "{{.status}}"
